### ISSUE TITLE
Firefox dev not detected?

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#119]

**Comment by evanwarner** [comment]
Firefox Dev shows in the menu of browsers, but there is no hotkey for it.

**Comment by will-stone** [comment]
Oh, someone contacted me on Twitter saying it wasn't working. I've not had a chance to look into it yet but thanks for letting me know that it's working for you.

As for the hotkey, that's by design. I realised I was going to run out of letters fast if I was to add a hotkey to every beta/alpha/dev/canary version of every browser. Therefore I made the decision to only put hotkeys on production versions. This is where someone screams "make it configurable!", so I'll pre-emptively answer that now... Dealing with settings is a pain in the arse. Let's all repeat that: _dealing with settings is a pain in the arse_. Why? Because it means a lot more user journey testing. The combinations of what people can do goes up drastically and can quickly lead to an unstable product. I like to take inspiration from the [elementary OS](https://elementary.io/docs/human-interface-guidelines#accessible-configuration) project, whereby they say that an app should have "sane defaults". Also I'm a big fan of _learnt behaviour_, which is why I always turn down requests to make a rules engine (making B open a certain browser for particular domains). I know you weren't specifically saying that Firefox dev needed a hotkey, but thought I'd jump on this quickly in case somebody else stumbles across this issue.

Thanks for using Browserosaurus 😘

**Comment by evanwarner** [comment]
That's cool, I got around the issue by making FFDev my "favorite" browser, letting me hit the return key to target it. The other browsers I use are all production versions with hotkeys.

But just to play devil's (user's?) advocate: rather than allowing assigning any key to any browser, how about the reverse: similar to how you've defined an assignable "favorite", what about having a small number of predefined hotkeys (like keys 1–4) that browsers can be assigned to. That way people who do frequently utilize non-production browsers have a way to make their browsers keyboard-targetable. This would also be super nice for people who primarily/solely use a keyboard to navigate on their computer.

Thanks for making Browserosaurus!

**Comment by will-stone** [comment]
I like the idea. Maybe, to keep from having to make a settings window, it could be just a case of hovering over a browser and pressing the number twice or "long pressing" the key and that sets the hotkey 🤔 I'll have a think about this. I'm gonna close this issue though, as I've just installed FF dev and all seems to be working well
