### ISSUE TITLE
Add mailto: support?

### ISSUE THREAD

**Issue by mindfulsource** [will-stone/browserosaurus#163]
Sometimes I click on a **mailto:** link on a website.

I typically have Google Chrome set as my macOS app. It's set via Mail.app's Preferences > General > 'Default email reader'.

Then, inside Chrome it's set for GMail.com to handle incoming mailto: URLs.

But sometimes I want another browser's GMail to handle email links if I'm working in a different profile. I don't want Chrome to open up just because I accidentally clicked on a pesky **mailto:** link!

Would it be simple to add mailto: alongside https: in browserosaurus?

**Comment by will-stone** [comment]
Hi. Thanks for using B and thanks for the suggestion. My worry about this is that I'd then have to support lots of mail clients too, showing a different set of browsers/mail-clients depending on the type of link clicked. I will have a think about it.

**Comment by mindfulsource** [comment]
Thanks. Indeed I do know it's always more complicated than what we see in the polished GUI.

This is mine, I have millions of weird browsers: https://i.imgur.com/IN4jPbs.png

Just noticed that it doesn't detect everything installed on my Mac, like Opera Developer edition. So this means you have to code in support for specific handlers for them to show up?

(Oh wow just noticed the keyboard shortcuts - what a time saver! <3 Can I request 'E' for Microsoft Edge, as seen in my screenshot?)

Thanks for whatever you have time to cook up. Much appreciated, and already awesome. I know simple features can open whole cans of worms. E.g. I'd ask you to allow us to set custom hotkeys for any browser, but I know that's an entire new section to code up. Whatever you do, this is great.

**Comment by will-stone** [comment]
Yeah, I ruled-out custom hotkeys sometime ago. The current hotkeys are for the latest version of browsers only (due to everyone having dev channels these days). Therefore, "e" is for Edge Beta, which I think is the latest.

Stick another issue in for Opera Dev edition and I'll look to getting it in.

**Comment by mindfulsource** [comment]
- I migrated to Edge Beta (by simply overwriting files from`~/Library/Application Support/Microsoft Edge Dev` into `~/Library/Application Support/Microsoft Edge Beta`) and I now can use 'E', thanks!

- Created issue for Opera Dev edition.

- Maybe adding mailto: is simpler than I thought: Many like me just want another browser's GMail to catch the email link, and that browser does all the work for passing it to a new GMail tab. So the only new code needed is to add *mailto:* as an incoming URI? Then you can add clients on a case-by-case basis. To keep it quiet, you could not advertise that you support email. :P

Thank you for the work! Prob will donate if you add in *mailto:*. I don't have much, but I appreciate it.

**Comment by will-stone** [comment]
And I appreciate all the constructive feedback, thanks!

I can certainly give it a go with the `mailto`, like you say, people don't need to select B as their default mail client if they don't want to.

If you'd like to try it yourself (as I won't be able to look into this until the new year), you should just be able to add a protocol here: https://github.com/will-stone/browserosaurus/blob/master/package.json#L132

**Comment by mindfulsource** [comment]
Thanks for the suggestion! I'm not willing to get my hands dirty enough to continue with trying the injection myself (do I have to either compile from my own source entirely, or unpack `app.asar` in the package contents?...I'm not really a developer / don't know much about Electron) so I'll wait for you to add it in and feel free to notify me here and close the issue I guess, and I'd donate some once done. :)

**Comment by will-stone** [comment]
I've been looking into this and I'm a little unsure on the request now. Are you saying that you want B to handle mailto links clicked on websites? In other words, in a browser? Because this wouldn't work. For example, you tell Firefox to send all mailto requests to Browserosaurus, you then click Firefox as the destination, Firefox sees it's a mailto link so opens Browserosaurus... === infinite loop. Browserosaurus can only "listen" for links clicked in other apps...

Or do you mean for mailto links in non-browser apps? Which apps in particular are you using that contain mailto links?

**Comment by mindfulsource** [comment]
Yeah, the most common scenario always:

- An email link on the contact page of someone's website. Instead of my usual GMail Google Chrome mailto: handler, I sometimes want to email it from another browser or Mail app. Like browsing, I have many profiles for emailing too.

Or it could even be a `mailto:` link in a standalone email program like:

- Microsoft Outlook.app
- Mail.app

Then other scenarios:

- There's an email link in any macOS program, e.g. the 'About' window in an app with a dev contact email.

- You have an email link in editable text in TextEdit, Notes, etc.

---

Ah, I didn't think of this issue. "1 Infinite Loop". How appropriate! I've thought of a way to avoid the loop, if you were interested in exploring it:

For email links, don't have B just forward the `mailto:` URL to a browser or mail app. The button actually performs a little applescript or URL string transformation to instruct the client to create an email itself.

(You could slowly add support for various clients just like for browsers.)

Does any other competing tool offer this? It'd be awesome if B was the first!

---

To send a `mailto:` link to a browser (at least for one's primary GMail, denoted by `0`):

Modify the URL string from the incoming `mailto:mail@example.com` to an outgoing `https://mail.google.com/mail/u/0/?view=cm&tf=1&to=mail@example.com&cc&bcc&su&body=%60&fs=1`.

---

To send it to Mail.app, code in to perform the following AppleScript:

```
tell application "Mail"
	
	set theFrom to ""
	set theTos to {"mail@example.com"}
	
	set theSubject to ""
	set theContent to ""
	set theSignature to ""
	set theAttachments to {}
	set theDelay to 1
	
	set theMessage to make new outgoing message with properties {sender:theFrom, subject:theSubject, content:theContent, visible:true}
	tell theMessage
		repeat with theTo in theTos
			make new recipient at end of to recipients with properties {address:theTo}
		end repeat
		
	end tell
	
end tell
```

(source: https://gist.github.com/youandhubris/9e292822e3db8f91df93234db092906e)

===

Microsoft Outlook.app example:

```
tell (current date) to get (its month as integer) & "-" & day & "-" & (its year as integer)
set MyDay to the result as text
set Mytitle to "Daily Email - " as text
set Mytitle to Mytitle & MyDay

tell application "Microsoft Outlook"
	
	set newMessage to make new outgoing message with properties {subject:Mytitle}
	make new recipient at newMessage with properties {email address:{name:"Name", address:"test@example.com"}}
	#make new cc recipient at newMessage with properties {email address:{name:"Name", address:"mail@example.com"}}
	
	open newMessage
end tell
```

(source: https://gist.github.com/gourneau/5946401)

---

If you're open to adding this new functionality, I could create individual GitHub Issues for some initial mail examples if you'd like.

**Comment by will-stone** [comment]
Let's call this Scenario 1:
> An email link on the contact page of someone's website. Instead of my usual GMail Google Chrome mailto: handler, I sometimes want to email it from another browser or Mail app. Like browsing, I have many profiles for emailing too.

This is the infinite loop. Browserosaurus cannot detect links clicked in browsers, because it _is_ a browser, of sorts. It sets itself as the default browser so that it can intercept links clicked in other apps then pass them on to the browser of your choosing. This means, if you were to tell Chrome to open mailto links in Browserosaurus (which is currently possible), and then you were to pick Chrome from B's picker, you'd send the link to Chrome which would recognise it as a mailto and then open Browserosaurus, if you were then to pick Chrome... ♾

Let's call this Scenario 2:
> Or it could even be a mailto: link in a standalone email program like: Microsoft Outlook.app, Mail.app

Not sure if this would be possible, it would require testing. The reason I say that is because mail apps would probably not open external apps when mailto links are clicked. It's like a browser opening all links in another app.

I wrote the above before reading your whole message but I'll leave it there for posterity. Thanks for all the research work, it really does help when looking to add a new feature. I am gonna make the call and say that I don't feel like mailto links are the right fit for this product. It opens-up a whole new branch of functionality and that just brings with it more testing and headaches. Also, mail clients are typically paid-for applications, and this being a free app means I am not in a position to support every FancySubscriptionBasedMail.app out there, and you know people would soon start asking for those.

Now, if someone would like to create Mailosaurus, I would be more than happy to help out. Let's keep the do-one-thing-well rule, and keep Browserosaurus to browsers.

**Comment by mindfulsource** [comment]
Yep, totally understand. Hope someone makes 'Mailosaurus' one day but obviously it's not as common a need as normal HTTP links. Thanks for considering.

**Comment by nebbles** [comment]
Ah I just read this thread - such a shame.

I had come to post a new feature request for handling `mailto:` links since I had found another app Bumpr (https://getbumpr.com/) which supports both browser and email links.

Unfortunately they aren't open source - because I prefer the look of B's UI to that of Bumpr. At a guess they are using their browser plugins to do some clever interceptions and pass-offs.

At the least, I would have hoped for something like scenario 2; where B becomes the default email app, and then it provides options for native Mac apps (and just doesn't allow sending to browser?).
