### ISSUE TITLE
Allow opening a link directly in an incognito/private browsing window in said browser

### ISSUE THREAD

**Issue by joel-tonuri** [will-stone/browserosaurus#174]
Hey Will, just thought of a potential feature which would definitely come in handy for me (and hopefully others!) - allow opening a clicked link directly in an incognito/private browsing window in said browser

It could be a separate option with text over the browser's logo which clearly marks it as private browsing, or the user could hold down a hotkey while clicking on the designated browser for it to open a link in incognito mode/private browsing.

I'm not at all sure what would be required on the technical side of this, nor am I sure if it's even possible, but hey, I'd like to see it in Browserosaurus.

Thanks!

**Comment by will-stone** [comment]
I've had a quick look into this and the issue here is that it's a different command for different browsers. For example, Chrome uses "--incognito" whereas Firefox uses "--private". It could mean a lot of potential manual work to support all browsers; see [here](https://github.com/will-stone/browserosaurus/blob/master/src/config/browsers.ts#L8) for a list of browsers currently supported by Browserosaurus. That's not to say we rule this out completely but it's probably not a small task as I can't imagine there's a programmatic way to find out each browser's private mode's command.

**Comment by joel-tonuri** [comment]
Thanks for the reply Will. How would I go about adding a separate browser option for incognito Firefox (using the --private flag) on my end?

**Comment by will-stone** [comment]
If you're looking to fork the code and add your own browser(s), I wrote [this comment](https://github.com/will-stone/browserosaurus/issues/170#issuecomment-576193982) on another issue which should help. You'll also need to [alter the command](https://github.com/will-stone/browserosaurus/blob/master/src/main/main.ts#L126) that is sent (using the aforementioned `--private` flag) for your custom Firefox browser.

**Comment by fnwbr** [comment]
Hey, I have started working on implementing this by holding down the `shift` key over in this pull request: https://github.com/will-stone/browserosaurus/pull/326

Feel free to assign the issue to me, Will. I'm planning to address all feedback from you and others on the PR and ultimately get this feature into Browserosaurus! 🙃

**Comment by will-stone** [comment]
This will be in the next release. Thanks @fnwbr 😎
