### ISSUE TITLE
Compact mode

### ISSUE THREAD

**Issue by kemayo** [will-stone/browserosaurus#182]
Could there be a non-fullscreen mode? I find the dimming of the screen quite distracting.

I feel this could work with a simple modification of the current behavior:

* Attach the blue bar to the browser-picker popup
* Don't dim the background

Drawbacks I can see:

* the blue bar would be smaller, so it'd be more likely that the URL would be cut off. However, I theorize that *most* of the value from the blue bar comes from seeing the initial domain, so it wouldn't be too distracting in practice.
* it'd be easier to miss the picker opening in uncommon cases like airdropped links where there was no direct user-interaction on the mac itself

**Comment by will-stone** [comment]
Thanks for the suggestion. The main problem is the second _drawback_ you mentioned. I have been iterating over how B is displayed for years now, and I prefer to improve rather than provide options. Options means more testing, usually for something I'll never use.

Your best bet for getting your desired layout is to fork the project. However, if improvements can be made, I'm happy to discuss them here. What is it about the dimming screen do you find distracting?

**Comment by kemayo** [comment]
The sudden brightness-change is mostly what gets to me, I think, along with the bounce of the blue bar along the entire top of my vision.

My normal setup is using a 27" monitor at a desk, so it's fairly easy for the screen to fill my field of vision -- it's plausible that this would be less of an issue on a laptop screen.

**Comment by will-stone** [comment]
I've released 9.3 which removes the bounce and fixes #181. I'll have a play around with making it more compact and without the backdrop. I want to make it look more native, anyway.

**Comment by will-stone** [comment]
I'm going to close this for now as I'm thinking of taking Browserosaurus in another direction. Keep an eye on the issues and/or my Twitter as I'll be releasing an RFC once it's ready for alpha testing.
