### ISSUE TITLE
Can we convert app URL links to URIs?

### ISSUE THREAD

**Issue by xlogix** [will-stone/browserosaurus#215]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to I'm trying to open a Zoom link at work. Because, in order to join a meeting I have to click a link, get redirected to a page, click a prompt to start a meeting, the Zoom desktop app needs to load. And then I finally get to the meeting.

**Describe the solution you'd like**
Maybe we can start detecting links and convert them to their URI equivalents and directly open the link through their designated app. The best thing is that Zoom already have [URL Schemes](https://marketplace.zoom.us/docs/guides/guides/client-url-schemes) just waiting to be implemented. 

I've been meaning to develop an app/integrate with collaboration tools (like Slack) to make this... But, I think Browserosaurus would be perfect for it. It can be a great value addition.

**Comment by will-stone** [comment]
Thanks for the suggestion. The struggle I have with app-specific feature requests is trying to measure the benefit gained vs the code and maintainability required. However, I'm happy to see a PR and we can see how it goes. My initial thoughts:

- This will need to support multiple app schemas so it can be extended for the next app schema requirement. A separate package for parsing links to their native counterparts could be useful and a good place to start:
`(url: string) => (uri: string | undefined)`
- The app in question will need to exist on the user's machine, otherwise the link won't work; the detection can be included in the whitelist. Therefore, we'll need a way to hide apps (from the tiles). This can just be an extra key in the config for now. Maybe introduce a `type` key:
`'tile' | 'schema'` to avoid the boolean trap if different types of apps turn up in the future.
- One of the benefits of B is that it prevents you from opening links that you didn't mean too. We need to make sure this cannot be used to abuse this protection, it might be worth having a button in the URL bar that shows when a link has been parsed and toggles the URL/URI when clicked.

**Comment by will-stone** [comment]
Hey, have you been able to take a look at this? I'm going to close this for now, but please reopen if you need to discuss anything before submitting a PR.
