### ISSUE TITLE
Backspace deletion is broken for some URLs with #

### ISSUE THREAD

**Issue by i0ntempest** [will-stone/browserosaurus#235]
**Describe the bug**
Say I have this URL:
https://trac.macports.org/ticket/60723#comment:8/agdsf?sdfasdfasd&jhgsadf
(https://code.videolan.org/videolan/libaacs/-/issues/6#note_65636 also works)
The first backspace hit will delete everything behind it and append a "null" to the end of the URL. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a URL with a # in it, open it in B
2. Hit backspace once
3. Notice everything after "#" is replaced with "null"

**Expected behaviour**
B should only delete one section and "null" shouldn't be added

**Screenshots**
![Screen Shot 2020-07-02 at 18 11 02](https://user-images.githubusercontent.com/16017904/86413514-65a6d900-bc8f-11ea-97d6-f37d2578c6af.png)
![image](https://user-images.githubusercontent.com/16017904/86413547-76efe580-bc8f-11ea-80ab-83787c4ea950.png)

**Desktop (please complete the following information):**
 - OS:
 macOS 10.15.5
 - Version 10.11.0

**Additional context**
Your test URL in the test file doesn't reveal this issue, which is prolly why it got through.

**Comment by will-stone** [comment]
Thanks. I found the null issue and fixed it right after releasing. However that is a bit of a weird URL as I'm guessing you will want it to behave like so:

```
https://trac.macports.org/ticket/60723#comment:8/agdsf?sdfasdfasd&jhgsadf
https://trac.macports.org/ticket/60723#comment:8/agdsf?sdfasdfasd
```

However everything after the hash is one element of a URL so it will go to this:

```
https://trac.macports.org/ticket/60723
```

Which is where I think we'll stay for now. People put all sorts of things in the hash just because they can. Imagine a URL like this:

```
http://example.com/#a?1//2???aaa/bbb
```

Each iteration through the deleter would be:

```
http://example.com/#a?1//2???aaa/
http://example.com/#a?1//2??
http://example.com/#a?1//2?
http://example.com/#a?1//2
http://example.com/#a?1//
http://example.com/#a?1/
http://example.com/#a
http://example.com/
```

In fact, I'm not even sure what rules to apply there, but let's say 8 deletes to get to the domain 🤷‍♂️

If, in fact, all you'd like is the bug fixed and all you needed was `https://trac.macports.org/ticket/60723`, then cool. But thought I'd explain my reasoning... just in case 😄

**Comment by i0ntempest** [comment]
Thanks for the explanation. Im no expert in http and I haven't seen a URL with /&? after a # irl, so yea current behavior should be good.
