### ISSUE TITLE
Order of the Browsers

### ISSUE THREAD

**Issue by Hugh0000** [will-stone/browserosaurus#245]
I have Firefox, Chrome & Safari installed and the show up alphabetically, however I would like to change the order displayed into the order I tend to use them, thanks

**Comment by will-stone** [comment]
Thanks for using Browserosaurus.

Bearing in mind that Browserosaurus now opens in the centre of the screen, I cannot see the benefit of reordering the tiles. Please can you elaborate as to why this will be useful.

**Comment by Hugh0000** [comment]
My brain works from left to right, so as a user my eyes look to the right and at the moment see the browser I least use, I would prefer to see the most important one on the left and least on the right, other user's brains possibly work right to left.  I am a mouse & trackpad user, I am not big into my keyboard shortcuts.  Just a thought, no big deal if it's too difficult to implement.  Thanks.

**Comment by will-stone** [comment]
I don't feel it's worth the time to add and maintain. In v9, it made more sense because the picker would open next to the mouse.

You can assign a tile to be your favourite, which binds the <kbd>space</kbd> key. I jump between mouse and keyboard too but I find that hitting the largest key on the keyboard is my usual workflow now.

Maybe I could make the favourite stand-out a little more, maybe it _should_ be on the left (I'll have a think about that one).

For now, I think the simplicity of predictable, alphabetical order is nice. Therefore I'm gonna say no to reordering, however, feel free to have a crack, submit a PR, and we can discuss it there.
