### ISSUE TITLE
Update checker

### ISSUE THREAD

**Issue by will-stone** [will-stone/browserosaurus#29]

**Comment by will-stone** [comment]
Hey @Jackymancs4. I've written an update checker. Fancy checking it over before I release it? https://github.com/will-stone/browserosaurus/tree/update-checker You can set your version number to one before v1.3.1 in package.json if you'd like to fool it into thinking you have an old version.

**Comment by Jackymancs4** [comment]
Very nice! I tested it and it work pretty well.
Would you like some considerations?

**Comment by will-stone** [comment]
Please. All suggestions welcome.

**Comment by Jackymancs4** [comment]
- I'm not sure if it is intended or still a WIP, but the update window seems a bit.. unprofessional.
My suggestions are to lower the font, to put a background a little darker, and I really would enjoy some extra information, like current version vs new version. It seems to much a whole window for a button/sentence.
One idea could be to merge this feature in the about window.
<img width="412" alt="schermata 2017-12-15 alle 19 38 08" src="https://user-images.githubusercontent.com/6209647/34055504-b480918a-e1cf-11e7-83d1-106166e843fb.png">

- Personally, I would prefer way more something like <img width="412" alt="schermata 2017-12-15 alle 19 28 09" src="https://user-images.githubusercontent.com/6209647/34055796-13f2586e-e1d1-11e7-94ba-03f1b02cc851.png"> <img width="218" alt="schermata 2017-12-15 alle 19 27 40" src="https://user-images.githubusercontent.com/6209647/34055797-141f00f8-e1d1-11e7-8f16-3662c540f25c.png">
The whole thing put in the menu.

- Since some people can have trust issues, I also would prefer that the button links me to https://github.com/will-stone/browserosaurus/releases/tag/{version} instead of the dmg.

- This one is not very correlated, but here it is.
<img width="411" alt="schermata 2017-12-15 alle 19 31 43" src="https://user-images.githubusercontent.com/6209647/34055957-a0939864-e1d1-11e7-9406-cae1f892977a.png">
As you see, there must be a problem with the default height as it spawns the vertical scrollbar.

**Comment by will-stone** [comment]
All good points, thanks. The About window is actually a package but maybe you're right and it's time for me to write my own.

**Comment by will-stone** [comment]
@Jackymancs4 The update checker isn't quite finished and I've got loads of code to clean-up but if you check the branch now, you'll see the direction I'm going: About in prefs window, with update checker in there. I won't have my Mac with me over Christmas so you won't see any updates until late next week or the new year. Feel free to send any feedback you have on my new approach though.
