### ISSUE TITLE
Showing up in cmd+tab Application Switcher now

### ISSUE THREAD

**Issue by stgarf** [will-stone/browserosaurus#292]
Hola,

Browserosaurus is showing up in the <kbd>cmd+tab</kbd> macOS Application switcher now however I don't really see the utility of this? Is this intentional?

I guess it makes sense to me if there are windows to cmd+tab over to, but thats not the case of Browserosaurus which is why I think it might be a bug.

If this isn't a bug, could you make this option toggle-able? Thanks!

<img width="1915" alt="Screen Shot 2020-09-06 at 16 43 31" src="https://user-images.githubusercontent.com/1694002/92337745-878e5480-f060-11ea-91f9-752726a4c9b5.png">

**Comment by i0ntempest** [comment]
Know issue of v11.1. The dev is working on fixing.

**Comment by will-stone** [comment]
This will be fixed by the upcoming v11.1.1 release. I did some research and I thought Electron had made this API to make menu-bar only apps: https://www.electronjs.org/docs/api/app#appsetactivationpolicypolicy-macos However, I found it didn't really do anything. So all I did, in the end, is call `dock.hide()` once the app is ready.
