### ISSUE TITLE
v11(.1?) forced auto-updates

### ISSUE THREAD

**Issue by eatstorming** [will-stone/browserosaurus#293]
Just noticed the bug mentioned [here](https://github.com/will-stone/browserosaurus/issues/288#issuecomment-687900676) about B always showing on dock/cmd-tab and came to check about it. Nice to know it's being looked into.

However, I also just noticed when I opened B that it was "Downloading update..." and now it shows me a label/link to Update - I believe this will install the update it was downloading moments before.

Please, no. I know users are awful with keeping things updated, but I'm not one of those. I usually keep my devices more updated than they would have with auto-updates on, but I like knowing when things are updated (and possibly delay that if I foresee potential problems due to the updates). Please do not go all Google/Microsoft on us with forced updates.

Actually, I just tested something else. Clicking on the Reload button makes B auto-download some update again.

Seriously, revert this. Or at the very least add an option for B to never behave like this.

**Comment by will-stone** [comment]
Hi. Yes the cmd-tab thing is a weird one and should be fixed in 11.1.1

I'm going to be rather frank, but please take this as someone who is passionate about thier app and not a slight on you, as it sounds like you are passionate about software too. I really do appreciate the feedback. However let's start with:

> Seriously, revert this.

Please never demand things in Open Source.

Right with that out of the way, let's chat about the update policy. Browserosaurus is an [Electron](https://www.electronjs.org/)-based app. Electron comes with a plugin called the auto-updater. It does what it says on the tin and is the easiest way to keep Electron-based apps updated. Unfortunately, the auto-updater is all or nothing.

Which nicely leads me on to... Google and Microsoft have business models. Be that subscriptions or ad revenue. Have you seen Browserosaurus's business model? ...yeah, it doesn't have one. I really like that my app updates when I publish it. So with all due respect, [You're in My World Now, Grandma](https://www.urbandictionary.com/define.php?term=You%27re%20in%20My%20World%20Now%2C%20Grandma) 😈 Seriously though, it's a free app. Know that it will stay maintained whilst I use it, and whilst I welcome suggestions, I'll forcefully (no pun intended) push back on demands.

**Comment by eatstorming** [comment]
😂

Alright. Sorry if I came across as demanding, but I believe you're reading way too much into it and reacting too strongly. I'll follow your request and leave you and your app alone, but as a last display that my intent was not to demand, but to raise a valid concern, I'll give you a couple of examples of things that maybe you did not consider when you implemented this behavior:

Data caps still exist and are likely way more prevalent than you think. Add to that how B is apparently re-downloading updates each time it is reloaded, this can mount up and bring bad news to a lot of people. "It's just < 7MB!" Yeah, for each update right now. Also for each time it reloads. Again, caps do exist.

Things just break, nobody is immune from making mistakes. Your B-staying-on-dock issue (thank you for fixing it) is a good example. I'd wager that due to Apple's "user-friendliness" it may be more likely that something going haywire and then auto-applied might trigger less savvy users to have issues with unexpected behaviors, but this is just speculation based on past experiences. YMMV.

But no worries, as I said I'll leave you alone. Sorry about 3 words triggering you this hard, it was not my intent.

**Comment by will-stone** [comment]
Please read this: https://github.com/will-stone/browserosaurus/issues/285 It'll show you why I'm getting fed up. But don't worry, you weren't _that_ bad.

Like I said, I appreciate the feedback, I'm just really not trying to please anyone. I wrote Browserosaurus for me. If it breaks, it breaks. The OS world is put under way too much pressure, for what is mainly a hobby for most.

If you'd like a go at improving the situation, the Electron project would probably welcome a PR that allows updates to be skipped.
