### ISSUE TITLE
Feature Suggestion: URL entry

### ISSUE THREAD

**Issue by badcat** [will-stone/browserosaurus#305]
I like the "Delete Section of URL" feature.  I wonder if that could be opened up to allow user entry? Either by direct edit or pasting a URL.  Thoughts?

**Comment by will-stone** [comment]
I've had [this request](https://github.com/will-stone/browserosaurus/issues/207) before. I really can't see the benefit. I would describe Browserosaurus as an in-between app, rather than one you deliberately activate. Please can you describe your use case?

**Comment by badcat** [comment]
Sorry - missed the previous request.  Sometimes when testing web pages, I'd copy the URL and then want to open the same URL in another browser.  Since it's on the clipboard, it seems like it would be a good feature to be able to paste it into Browserosaurus' URL bar and choose the browser I want to open. Seeing the amount of select, copy/paste interactions are the same, I guess it's not worth it.  I suppose the request stems from the concept that the URL bar already allows deleting part of a URL and copying URLs out of "B".

**Comment by will-stone** [comment]
Maybe I need to think of a better design that suggests the URL bar is read-only. Maybe people are used to seeing URL-bars with buttons and assume they are interactive 🤔 I think with me changing the menubar button to launch B (rather than show a menu) it has encouraged people to use it as a rudimentary app launcher, this was obviously never my intention, but I'd rather not change it if people find that useful. To be honest, it's incredibly useful to me too, when developing Browserosaurus. I think we'll leave out paste for now.

Thanks.
