### ISSUE TITLE
Open in background does not work properly

### ISSUE THREAD

**Issue by nuTTeLLo** [will-stone/browserosaurus#307]
When opening a link via Browserosaurus with the alt/opt key pressed, it brings the browser window to the front, only it is unfocused (for Firefox and Safari). Chromium based browser opens it focused.
Was expecting this to be opening in the background without bringing forward the browser window or being focused.

Tested on v12.1.0 with Mac OSX 10.15.6 with Firefox, Brave and Safari

**Comment by will-stone** [comment]
Okay, I think I've fixed this for Firefox and Safari and it'll be in the next release. As for Chromium-based browsers... all B does is run the open command followed by the `--background` modifier, e.g.

```bash
open 'https://browserosaurus.com/' -b com.brave.Browser --background
```

If this doesn't work in the terminal, it won't work in B, and you'll need to log this issue with the Chromium or browser projects.

Thanks for spotting the bug. For posterity: it was because I was no longer running `electron.app.hide()` after running `browserWindow.hide()`.

**Comment by will-stone** [comment]
PS I know this isn't working with hotkeys. I'll open a new issue for this.
