### ISSUE TITLE
No browser selector on first-launch

### ISSUE THREAD

**Issue by houndtt** [will-stone/browserosaurus#391]
It seems like in the latest version of Browserosaurus (v 14.0.2), the initial launch seems to not show the browser selector. If you go into the preferences and refresh it then works fine. The following video shows what I mean:

https://user-images.githubusercontent.com/943378/115849088-8b55c800-a3f2-11eb-8eda-46348087bcec.mov

I am running MacOS Catalina (v 10.15.7) on a iMac (27-inch, Late 2012)

**Comment by will-stone** [comment]
Thanks @houndtt. Unfortunately I can only support the version of macOS that I use which is 11.2.3. Please reopen if you see this issue happening with Big Sur.

**Comment by badouralix** [comment]
Hi @houndtt. I am running with the exact same setup as you, and can reproduce the issue. I've noticed that reinstalling v14.0.1 fixed the issue, so I guess the problem is somewhere in https://github.com/will-stone/browserosaurus/compare/v14.0.1..v14.0.2

I wonder whether it is possible that `ready-to-show` never fires, and thus `bWindowIsReadyToShow` remains `false` until we click on the refresh button.

**Comment by houndtt** [comment]
Hi @will-stone, I have to run a few more tests but it appears that the new version https://github.com/will-stone/browserosaurus/releases/tag/v14.4.0 seems to fix the issue for me on macOS Catalina!

**Comment by will-stone** [comment]
@houndtt Awesome! Thank you for testing (and sticking with Browserosaurus) 😄
