### ISSUE TITLE
Equally fill the window with items

### ISSUE THREAD

**Issue by maharjanaman** [will-stone/browserosaurus#405]
Without the carrot (contribute) icon, there is this black space on the window. 😅
<img width="536" alt="Screen Shot 2021-06-05 at 13 30 23" src="https://user-images.githubusercontent.com/14164484/120884435-f81fcd00-c602-11eb-8ebb-79f69034e1eb.png">

I feel like we're asking for too much but is it possible to fill the window width giving equal spacing for the items?

**Comment by will-stone** [comment]
Hi @maharjanaman. The reason the width used to be for four tiles was because the URL would get too squashed/truncated. However, the URL now spans on to three lines:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/654103/120887011-a5d1b280-c5e8-11eb-8637-16cc12f5f618.png">

So I could set the min-width to fit three tiles instead. I'll have a look to see how this change will affect other parts of the app. For example, the new support message component might need updating for this new smaller width.

Otherwise, I like to fill the space too, and I usually just download another browser for fun. Sometimes I even end-up using them. e.g.

Tor - for ultimate privacy.
Edge - to see how MS are getting on with their browser.
Polypane - the best webdev browser there is.

**Comment by maharjanaman** [comment]
Thanks for quick response and considering the requested changes.

**Comment by will-stone** [comment]
I've had a play around with this and it gets quite cramped quickly. Stacking buttons and reducing padding just doesn't feel right. I'm going to close this for now but if you come up with a design that you think would work, please feel free to post back here and I'd be happy to consider it for a major release.
