### ISSUE TITLE
PickerWindow should appear on active screen

### ISSUE THREAD

**Issue by long-lazuli** [will-stone/browserosaurus#46]
Actually, browserosaurus's pickerWindow appears on main screen.
I think it should appear in the screen where the cursor is.

**Comment by will-stone** [comment]
It should already do that; it certainly did last time I checked. It's what this line should do: https://github.com/will-stone/browserosaurus/blob/master/src/renderers/utils/UrlListener.js#L28

I won't be able to check until tomorrow; where I can check on my multi-monitor setup at work.

**Comment by will-stone** [comment]
Hang-on. Do you mean screens or workspaces?

**Comment by will-stone** [comment]
Tested workspaces and that seems to be working ok, so you must mean screens; I'll test that tomorrow. Thanks.

**Comment by will-stone** [comment]
On my multi-monitor setup at work, this works just fine. Please can you post which version of B and macOS you're using? Try again after a full restart. And then a video of the bug would be great. I use Monosnap for my screen captures and highly recommend it (it's free).

**Comment by long-lazuli** [comment]
I just updated the version on my laptop. so v3.01.
I restarted it. I experience the same.

But it is because I click on a app in fullscreen.

When I click on a link in a fullscreen app on the external screen, browserosaurus's pickerwindow appear on my laptop screen.

I'm not sure if you can put a window over a fullscreen app...

**Comment by will-stone** [comment]
Ah full-screen, yeah that's a weird one in macOS. I'll see if anyone else has reported that in Electron's repo.

**Comment by will-stone** [comment]
Looks to be an upstream problem: https://github.com/electron/electron/issues/1836

Let me know if you find a solution.

**Comment by will-stone** [comment]
This bug also affects B if this is unchecked:

<img width="780" alt="mission control 2018-03-13 14-52-06" src="https://user-images.githubusercontent.com/654103/37349392-377629c2-26ce-11e8-940c-2495b203326f.png">

**Comment by will-stone** [comment]
The only way I can see to fix this is to change the behaviour of the picker; moving it to where the mouse is. This is actually how the first (probably pre-release) version of Browserosaurus worked and I changed it to a more predictable center-of-screen. I'm not adverse to placing it next to the mouse position, in fact I quite like it; it means if you don't use keyboard shortcuts, the browsers are within closer reach. I need to play around and get it working well. One thing I'd like to do it overlay the screen with a semi-transparent dimmer so that the position of the picker stands out more. I've just figured out the basic theory behind doing this, hopefully I'll release this in the next version.

**Comment by long-lazuli** [comment]
I kind of like it too.
clicking is done by the mouse; so clicking close to the first click is fine for me.

**Comment by will-stone** [comment]
Cool. I'll probably release it as part of v4, and without the dimmer/backdrop, as in my tests, I've found it slows down the appearance of the picker and I want that to always be instant. I'm getting close. v4 will include copy-to-clipboard functionality too.

**Comment by will-stone** [comment]
Feature will be in v4
