### ISSUE TITLE
Custom order of browsers

### ISSUE THREAD

**Issue by w3code** [will-stone/browserosaurus#5]
Hi, thanks for this great tool!

I have a suggestion, it's not very important, but could be a nice implementation: a customized order of the different browsers. Let's say: the user could decide, which browser is in which order, maybe with drag&drop or so.

**Comment by will-stone** [comment]
Thanks. I do want to start looking into adding settings to my Electron apps but just haven't had the time yet. I'll happily look at pull-requests if you would like to have a go yourself. You'll quickly see that there's not a great deal to the code and all should be fairly obvious.

However, I'm not sure how important _order_ is at the moment, as the shortcuts use dedicated keys rather than an arrow/enter selection. Otherwise, using the mouse, is a case of muscle memory, where I think alphabetical order is sensible. Happy to hear the case for reordering though.

**Comment by w3code** [comment]
Yeah, of course, for now I'll let play my muscles. :-)
As I mentioned, it's not important, just a nice feature.
Unfortunately I haven't the time at the moment, too, to go with it myself.
So, no stress! ;-)

**Comment by will-stone** [comment]
I've decided that alphabetical order is acceptable. Please let me know if you have any other suggestions, though.

**Comment by EdenSG** [comment]
It would be cool if the app could keep track of what browsers the user selects most often and then present those first... Maybe even optionally keeping track of urls so that it can suggest browsers based on what browser the user tends to open similar urls with.

If I have time, I'll play around and see what I can do.

**Comment by will-stone** [comment]
But what is the benefit? If browsers were selectable with arrows/enter then I kinda get it, otherwise I think we’re just messing with muscle memory.

**Comment by EdenSG** [comment]
Mental load: if the browser you most commonly use is right where your cursor is and/or you just have to hit enter, there's no need to remember what shortcut a browser has or where it is in the list. Maybe if there's enough certainty connecting a particular url to a browser, browserosaurus could even bypass the browser selection and immediately open the right browser.

Although maybe if a user holds option or something like that it could always show the selector.

**Comment by will-stone** [comment]
Wow! That's a lot of new features. I'd say if the user has a favourite browser, they use the upcoming config to map the keyboard shortcut to "enter". Also this config will allow the user to order the browsers as they wish.

I tried "open at cursor" and whilst it worked, it over complicated matters and introduced many edge cases to account for; going for Spotlight/Alfred middle-of-the-screen approach was much simpler and predictable.

I'm really not fussed about adding a "learning" aspect to the app, let's keep it simple. Also this comes down again to muscle memory (of sorts). For example, B opens on URL click, I now expect it to open. If B started "learning" which URLs I tend to send to which browsers, I'd have to predict and overrule that. It's just not what the app is for. It sounds like you're describing features of [Choosy](https://www.choosyosx.com/), please check-out that app if you're interested in creating _rules_.

But don't let me dampen your enthusiasm! Keep the ideas coming :-)

**Comment by EdenSG** [comment]
Just throwing ideas out there :)

I'll play around with it, but I see your point — simpler may be better in this case. I actually used a custom Hammerspoon config for a while, but I was never really happy with the amount of config I needed to do what I wanted.

Interesting point about muscle memory, I probably just need to spend more time with it.

**Comment by will-stone** [comment]
Hi. Please note that custom order can now be achieved in v1.3.1 http://wstone.io/browserosaurus/ using the new preferences window (found in the menubar icon menu).
