### ISSUE TITLE
Missing browser(s)

### ISSUE THREAD

**Issue by GaldanM** [will-stone/browserosaurus#50]
I just found out about Browserosaurus because I was looking for an alternative to Choosy. Your solution seems to be a lot better but it can't detect Firefox Dev Edition.

I'm looking forward for Browserosaurus to detect it ! 😄

**Comment by GaldanM** [comment]
Oh I see, in fact, I renamed the app in Applications from FirefoxDeveloperEdition to Firefox Dev, this is why it couldn't be detected ! I changed it back to FirefoxDeveloperEdition and it work now ! Sorry for the inconvenience..

**Comment by will-stone** [comment]
Ah. No worries. I don't think there's much I can if people rename the apps, but thanks for bringing this to my attention; I thought the apps' IDs were at a more meta level. Dev addition still installs with "Firefox Developer Edition" instead of the current "FirefoxDeveloperEdition" so that will have to change. Bear in mind that when this is fixed, you'll lose the browser again and will have to rename it "Firefox Developer Edition".

**Comment by GaldanM** [comment]
That's ok, thanks for the warning and thanks for this app, works like a charm !

**Comment by will-stone** [comment]
Fixed in v3.0.2, please update your app name to default: "Firefox Developer Edition"
