### ISSUE TITLE
Feature request: Enable support for Chrome Profiles

### ISSUE THREAD

**Issue by israelroldan** [will-stone/browserosaurus#56]
First of all, thanks for putting together this tool, it is extremely useful!

I'd like to explore an optional feature to allow listing all available Chrome profiles so that you can choose which profile you'd like to open the link with.

I'm filing this as a feature request to ask for comments and keep track of the efforts before the PR.

**Comment by will-stone** [comment]
Interesting. As long as there's a command to get a list of profiles then this should be possible. Let me just merge v4 into master. I've been using it for quite some time and just never got around to releasing it. I'll post here when it's done.

**Comment by will-stone** [comment]
Ok, all merged. I'll write-up some docs at some point but adding new activities shouldn't be too difficult, see `src/config/activities.js`. However, what you are suggesting is adding dynamic entries, so I'll be keen to see how you go about that.

**Comment by will-stone** [comment]
I've realised that this could add a lot of verticality to the picker. Therefore, I've started work on a more compact picker, it should be finished soon.

**Comment by israelroldan** [comment]
@will-stone thanks for your comments.

There's currently no official way to list the available user profiles (other than digging around in the application data directory) so I'll start with that. Since I think that falls out of the scope of `browserosaurus`, I'll come back with this PR once that small module is ready to roll.

Thanks for the quick reply, it is really nice to interact with an alive and well project! :) 

👍 💯

**Comment by israelroldan** [comment]
In case anyone wants to pick this up in the meantime, I have just published [`chrome-profile-list`](https://www.npmjs.com/package/chrome-profile-list) to list available Google Chrome profiles.

I'll work on this feature some time next week.

**Comment by will-stone** [comment]
Nice work! However I can't seem to get the open command to work. If I run this to get the profile dir:

```sh
❯ npx chrome-profile-list-cli
npx: installed 84 in 2.553s
[
    {
        "name": "Will",
        "profileDir": "/Users/will/Library/Application Support/Google/Chrome/Default"
    },
    {
        "name": "Guest",
        "profileDir": "/Users/will/Library/Application Support/Google/Chrome/Guest Profile"
    }
]
```

And say I want to open a URL with the "Will" profile, I would have thought the command would be:

```sh
❯ open "https://apple.com"  -a "Google Chrome" --args --profile-directory="Will"
```

but in fact, it is:

```sh
❯ open "https://apple.com"  -a "Google Chrome" --args --profile-directory="Default"
```

I got that from here: https://superuser.com/a/377195

Therefore, it seems like the last part of the "profileDir" would be useful to keep in a key ("profileDirName"?) as this seems to be the bit required for the command.

**Comment by israelroldan** [comment]
You're right! Fixed with [v1.0.0](https://github.com/israelroldan/chrome-profile-list-cli/releases/tag/v1.0.0)

**Comment by will-stone** [comment]
Awesome. I wonder, would you be able to access the profile picture? i.e. these:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/654103/42499455-be370660-8426-11e8-9d31-ad54c8d1c6e6.png">

My thinking is that now I've moved to an icon-based picker, I could overlay these on Chrome logos to denote each profile.

**Comment by israelroldan** [comment]
Done with [chrome-profile-list-cli@1.0.1](https://github.com/israelroldan/chrome-profile-list-cli/releases/tag/v1.0.1):

```
[ { displayName: 'User',
    profileDirName: 'Default',
    profileDir: '/Users/username/Library/Application Support/Google/Chrome/Default',
    profilePictureUrl: 'https://x.googleusercontent.com/path/to/profile/picture.jpg' },
  { displayName: 'Guest',
    profileDirName: 'Guest Profile',
    profileDir: '/Users/username/Library/Application Support/Google/Chrome/Guest Profile',
    profilePictureUrl: null },
  { displayName: 'Person 1',
    profileDirName: 'Profile 1',
    profileDir: '/Users/username/Library/Application Support/Google/Chrome/Profile 1',
    profilePictureUrl: 'https://x.googleusercontent.com/path/to/profile/picture.jpg' } ]
```

**Comment by will-stone** [comment]
I still want to add this, it won't make v5 but I'm still keeping it mind.

**Comment by brettgoss** [comment]
I experimented with this a bit, but it looks like Chrome will ignore the `--profile-directory` argument if an instance of Chrome is already running. You can work around this by specifying the `-n` flag to force opening a new instance, but that's less ideal since it would effectively limit the user to choosing between 'Open link in last touched profile' and 'Open link in new window with selected profile'.

For me, that's better than nothing though, so I'll push up a branch on my fork once I can get the UI figured out.

**Comment by will-stone** [comment]
Thanks @brettgoss. I have been playing with this too and have been struggling, so any help will be greatly appreciated. I'm not really sure how to get this into my config mechanism without crapping on a lot of code. I'm certainly keen to see your approach.

**Comment by brettgoss** [comment]
@will-stone - I have a branch started here: https://github.com/brettgoss/browserosaurus/tree/add-profile-selection-with-chrome. I haven't yet figured out how the UI will work for it, but I have the profiles listed on the activity for Chrome. It still looks like relaunching the browser is going to be the only option for getting it to open with a specific profile, but maybe that will change one day.

**Comment by will-stone** [comment]
Nice, thanks. So are you saying we're a little limited by Chrome's behaviour?

**Comment by lemieszek** [comment]
For anyone wondering, as for 2020-10-13, chrome still ignores `--profile-directory` flag when it's already opened.

**Comment by kukat** [comment]
👀

**Comment by huyz** [comment]
@lemieszek It seems that `finicky` is able to figure it out even if the profile is already opened: https://github.com/johnste/finicky/wiki/Configuration

**Comment by will-stone** [comment]
@huyz Finicky isn't written using Electron/Node, and has access to lower-level APIs.

**Comment by huyarts** [comment]
@will-stone is there a way to invoke Chrome with custom arguments so that I can specify `--profile-directory`

**Comment by huyz** [comment]
@will-stone Is there a way to invoke Chrome with arguments so that I can specify `--profile-directory`?

**Comment by will-stone** [comment]
@huyz if you have a certain profile you always want to use with B, your best bet is to fork B and hard code it yourself.

**Comment by nicoburns** [comment]
Hi @will-stone. I've just installed Browserosaurus and I'm liking it so far. But my main two "browser" are my personal and work Chrome profiles, so it'd be really handy to have this feature.

I did a bit of digging and it seems that Finicky isn't doing anything other than shelling out. Specifically it appears to be calling:

`open -b com.google.chrome -n --args --profile-directory="Profile 1" https://google.com`

(see: https://github.com/johnste/finicky/blob/master/Finicky/Finicky/Browsers.swift). This is working fine to open an existing instance of a profile for me (both with finicky and when run on the command line).

Also, the profile pictures seem to be stored in a file called `Google Profile Picture.png` in each profile directory if that helps.

**Comment by lemieszek** [comment]
Awesome find @nicoburns!
next step: get the profiles

Google store profiles under those names:
Default - you gessed it - default profile
then start counting from 0 on "Profile"
```bash
ls ~/Library/Application\ Support/Google/Chrome | grep '^Default\|^Profile\ '
# Default
# Profile 0
# Profile 1
# Profile 2
```

then we need usernames and icons?
its there in JSON (for default user with avatar):
```bash
cat Default/Preferences | jq '.profile | .name, .gaia_info_picture_url, .avatar_index, .using_default_avatar'
# "lemieszek 🍓"
# "https://lh3.googleusercontent.com/a-/AAuE7mCEEGsAg2x8Bsb-rPwmzHKjLnM00q9g_LVpEjsdvYk=s256-c-ns"
# 0
# false
```
seems normal right?
but for other profiles:
```bash
cat Profile\ 1/Preferences | jq '.profile | .name, .gaia_info_picture_url, .avatar_index, .using_default_avatar'
# "Cat"
# null
# 27
# null
```
And yet, I have added and then removed some profiles. Yet preferences stayed there, with old names.
Even that I only have 2 profiles available in chrome:
![image](https://user-images.githubusercontent.com/37555757/102822816-0faf2480-43da-11eb-8779-3b559812488e.png)

**Comment by will-stone** [comment]
Thank you all for the effort that has gone on here. I was going to announce this after releasing v13 but as this issue has seen some sudden progress, I feel I need to let you know now to avoid future disappointment. After the release of v13, Browserosaurus will be considered Public Feature Complete. I started this project to solve a simple problem: open the browser of my choice when I click a link. Over the last three and a half years, I have added [several](https://github.com/will-stone/browserosaurus/issues/54) [community-requested](https://github.com/will-stone/browserosaurus/issues/174) [features](https://github.com/will-stone/browserosaurus/issues/228) and support for [many browsers](https://github.com/will-stone/browserosaurus/issues?q=+is%3Aissue+label%3A%22add+browser%22+) that I do not use. I have received a roller-coaster of [recognition](https://mac.softpedia.com/get/Internet-Utilities/Browserosaurus.shtml), [praise](https://www.producthunt.com/posts/browserosaurus), and [insults](https://github.com/will-stone/browserosaurus/issues/285) (by the way, [not](https://github.com/will-stone/browserosaurus/issues/219) saying [thank-you](https://github.com/will-stone/browserosaurus/issues/100) for a [feature](https://github.com/will-stone/browserosaurus/issues/139) or [bug fix](https://github.com/will-stone/browserosaurus/issues/307) you've requested, is an insult). Browserosaurus has achieved what it set out to do, and is my favourite hobby, and whilst I am grateful for the public buzz that Browserosaurus has garnered over the years, I feel I must now draw a line in the sand with regards to community requests to support new features. I hope that you will respect this decision and the many hours of development that have already gone into this freely available app. I will of course still support Browserosaurus, and any features I feel I need from it for as long as I use it, but I will not be accepting any more browser or feature requests. I will also continue to release these updates publicly as long as my GitHub sponsorship covers the cost of the yearly Apple Developer account that is required to notarize the app so that it can work on your machine.

Lastly, a big thank-you to all that have been involved in helping make Browserosaurus through PRs and bug squashing, and to all the projects that it relies upon.

This notice will be moved to a CONTRIBUTING.md shortly and issues will be triaged accordingly.

Now, you are probably disappointed that this feature will not be making it to Browserosaurus. Please fork the project, that is what Open Source is all about. Make something with your personality, strip out the stuff you don’t like, have fun with your own brand (I once suggested the name Browseratops to someone who wanted to make a Linux port… they didn’t, by the way, in case anybody fancied trying that too). You may want to check out the (unfinished) `big-sur-design` branch first, I think you're going to like the upcoming changes.

😘

**Comment by will-stone** [comment]
Added contributing file: https://github.com/will-stone/browserosaurus/blob/master/CONTRIBUTING.md

**Comment by prewk** [comment]
Thanks a bunch for all the work you've done @will-stone, Browserosaurus has been super useful to me!

**Comment by lemieszek** [comment]
🙏🏽 Thank you @will-stone for all your work and this awesome app!
I wish you all the best in the future! ❤️

**Comment by WorkInProgress-Development** [comment]
Just wanted to hijack this thread to add on my thanks to @will-stone for all the effort and work with this amazing tool, which I am using many, many times a day. All the best in your future endeavours.
