### ISSUE TITLE
spinning circle in V. 20.x

### ISSUE THREAD

**Issue by fidpa** [will-stone/browserosaurus#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

It seems incapable to find Browsers and just shows this spinning circle. I tried several things including the homebrew install, complete re-install, logging out and in, restarting the machine, granting rights in the security settings, etc. pp. … without success.
![MBA 2](https://user-images.githubusercontent.com/97551772/227766749-6a7562c4-0c92-46dd-8f7c-8ab53bfe5fe9.png)

### Expected Behaviour

Offering existing Browsers to choose from.

### Steps To Reproduce

Click a link and have Browserosaurus set as your standard browser ;-)

### Browserosaurus version

20.2.0

### macOS version

13.2.1

### CPU Architecture

ARM

### Anything else?

It works fine on my Intel MacBook running macOS Monterey.

**Comment by fidpa** [comment]
Version 19 worked fine, by the way

**Comment by billyjacoby** [comment]
I'm having this exact same issue and can't figure it out.
The apps window in preferences also shows spinning and preferences shows 0 apps available

**Comment by will-stone** [comment]
Hi @fidpa, @billyjacoby. Where on your filesystem are your browser apps stored? B only scans `/Applications`. Although it should at least find Safari 🤔 Could you please try deleting `~/Library/Application\ Support/Browserosaurus` and restarting B?

**Comment by billyjacoby** [comment]
Sorry for the short initial response. This was working just fine about a week ago then just started seeing the spinning circle of death a few days ago. I am on the latest beta version of macOS (13.3), so that could definitely have something to do with it.
Deleting the Application Support folder didn't seem to do anything. I plan on building from source and adding some logs in to see if I can provide more help.
If you have any ideas for where to look let me know!

**Comment by billyjacoby** [comment]
Okay found a solution, but as I'm not terribly familiar with Electron I'm not sure how "good" it is. It seems that for some reason the `execSync` command will throw an error even if it shouldn't have? Referenced [here](https://github.com/nodejs/node/issues/9870) but not for a while.

The solution I found basically forces the shell script to return true all the time which is definitely problematic as well, but at least it will allow the application to continue instead of just showing a loading spinner - [StackOverflow Fix](https://stackoverflow.com/a/45493009)

PR: fix: skip error from shell script #631

**Comment by will-stone** [comment]
Closing. Let me know if this error persists even after v20.2.1
