### ISSUE TITLE
Option for faster opening from keyboard

### ISSUE THREAD

**Issue by bendem** [will-stone/browserosaurus#80]
This piece of code introduces an arbitrary timeout before opening the link when selecting a browser with the keyboard. Is there a way to make that optional? It really adds a feeling of slowness and I don't really care for the application to give me feedback on which browser I chose when said browser will open anyway.

I'd just open a PR to remove the timeout, but I'm guessing it's there for a reason and I'm not comfortable enough with react/electron to add an option.

https://github.com/will-stone/browserosaurus/blob/82b505dd7ce50b672a711c6640ef72bb057a7549/src/picker/app/activity/activity.container.js#L27-L30

**Comment by will-stone** [comment]
200ms would be a nice delay compared to what happens on Mojave (#77). That aside, yes, I put that in for visual feedback; when it opened immediately, it just didn't feel right. For example, let's say you accidentally hit a keyboard character, it's nice to know which app is about to open. I think 200ms is fair. I read somewhere that all UI interactions (that require feedback) should be between 200 and 300ms.

To be honest, until #77 is fixed upstream, I won't be adding or changing anything to this app because even I am not using it. However, adding options isn't trivial: you have to persist (store) the config, decide where in the preferences to house the option, then pass down conditionals to the app. In other words, when I used Browserosaurus, I liked the mini delay and so this won't be changing. You are more than welcome to fork and build your own. The instructions are on the README.

**Comment by bendem** [comment]
Yup, I'm already using a patched version, just thought I would ask if it was something that would be considered upstream.

I'll leave the patch for those who are also interested.

```patch
From e95a879580219895ef741364b05117fef1b0f101 Mon Sep 17 00:00:00 2001
From: bendem <online@bendem.be>
Date: Fri, 12 Oct 2018 09:44:04 +0200
Subject: [PATCH] Remove timeout before opening browser
---
 src/picker/app/activity/activity.container.js | 7 +------
 1 file changed, 1 insertion(+), 6 deletions(-)

diff --git a/src/picker/app/activity/activity.container.js b/src/picker/app/activity/activity.container.js
index b2329e0..52551d8 100644
--- a/src/picker/app/activity/activity.container.js
+++ b/src/picker/app/activity/activity.container.js
@@ -23,12 +23,7 @@ class ActivityContainer extends Component {
   }
 
   hotKeyOpenActivity = () => {
-    this.setState({ isActive: true }, () => {
-      setTimeout(() => {
-        // timeout is to show the active state briefly before opening activity.
-        this.runActivity()
-      }, 200)
-    })
+    this.runActivity()
   }
 
   /**
-- 
2.19.1
```
