### ISSUE TITLE
Brave Browser not being detected

### ISSUE THREAD

**Issue by doms** [will-stone/browserosaurus#85]
👋 

Brave Browser isn't detected by Browserosaurus 🤔  I'm using the latest version (4.4.0)

<img width="1005" alt="screen shot 2019-01-07 at 5 42 07 pm" src="https://user-images.githubusercontent.com/8808097/50800118-7ba72980-12a4-11e9-8e11-4a4832ca8f9e.png">

---

I tried this: https://github.com/will-stone/browserosaurus/issues/79#issuecomment-428868965 and saw this:

https://github.com/will-stone/browserosaurus/blob/82b505dd7ce50b672a711c6640ef72bb057a7549/src/config/activities.js#L7-L12

If I do `open "https://github.com" -a Brave\ Browser`, then it seems to work.

It seems that maybe B is looking for `Brave`, when instead it should `Brave Browser` ? They must have changed the name in between the last commit and now 😆 

I could submit a PR to use `Brave\ Browser` 😄

**Comment by will-stone** [comment]
Hi, thanks for the enthusiasm but someone's already beaten you to the punch: https://github.com/will-stone/browserosaurus/pull/82 I'll merge it soon. I've just been struggling with this project due to this bug with Electron: https://github.com/will-stone/browserosaurus/issues/77 (https://github.com/electron/electron/issues/16166) I know it's annoying when maintainers do not maintain; I promise I'll merge and release those PRs soon.

**Comment by doms** [comment]
@will-stone 

ahh, I seemed to have overlooked that, my apologies! No worries about not maintaining, especially if a bug on the core part of the project is the blocker. I appreciate the overall project, and the timely response. 💯

**Comment by will-stone** [comment]
Update in v4.5.0
