### ISSUE TITLE
[Feature Request] Shift-click to open with default browser

### ISSUE THREAD

**Issue by selfagency** [will-stone/browserosaurus#98]
It would be great if you added a modifier key action, like shift-click, that automatically opens the link in the default browser instead of showing you the modal window. It would also be great if there were an option to reverse this functionality, so that links are automatically opened in the default browser when you click and the Browserosaurus modal opens when you shift-click.

**Comment by will-stone** [comment]
Hi, thanks for using Browserosaurus. This might be possible. It would require you to hold shift until the link has been sent to B (which is quite quick so shouldn't be a problem). I can definitely see the value with this. However, I've put all feature requests on hold until I can sort out the [notarization issue](https://github.com/will-stone/browserosaurus/issues/96). I'll come back to this though.

**Comment by will-stone** [comment]
I’ve been thinking about this request: I am very much of the opinion that apps should provide as little preferences as possible and be ready to use out-of-the-box. Also, I feel there’s less cognitive load of clicking a link, opening the picker, and quickly moving the mouse a few pixels to hit the favourite (or quickly tapping enter) than over time learning to hold shift on every link until that one time you didn’t mean to and by then it’s too late and you’ve opened your favourite browser.

One idea I had was the the picker could be moved a couple of pixels over so that the favourite is always under the mouse on open, thus allowing you to essentially slow double click to always open in favourite. This would mean you would subconsciously know that on first click the same thing is always going to happen (and this is what I think is important) then if you mean to open in a different browser you’ve got that split second pause to readjust, or quickly click again to carry on the journey. There’s another issue open requesting for opening links in the background which I think would go nicely with my suggested solution to this problem. What are you thoughts?

**Comment by selfagency** [comment]
IMHO I think having to wait for the pop-up when I don't really need it 90% of the time is bad UX.

**Comment by will-stone** [comment]
If you don't need it 9 times out of 10, Browserosaurus probably isn't the tool for you. One of the reasons I like the picker to show every time is so that I can essentially back-out of opening _any_ browser by hitting the `escape` key. This really suits my workflow, and knowing this will happen 100% of the time ensures I follow the correct journey each time I click a link (or a link is opened by my terminal).

To be honest, I find describing the whole functionality of an app (and years of work of iterate and improve) in a one liner as "bad UX", is rather rude. Especially after I've offered-up a full explanation of _my_ UX thoughts, a long with what I thought would be a fairly nice compromise. 

If you'd like to implement your desired functionality, I suggest you start with [preventing the AShow action from firing](https://github.com/will-stone/browserosaurus/blob/master/src/picker/App.tsx#L161) by using `mousetrap` to listen for the shift key.

Good luck, and please don't take be perturbed to ask for other features.

Happy coding 😘

**Comment by selfagency** [comment]
I apologize for giving offense as it wasn't intended. I shouldn't have been so terse. I have used multiple tools along the lines of yours including [Bumpr](https://getbumpr.com/) and BrowserFreedom and, of the apps I've tried, I like your UI and UX the most. But I believe tools should not be so opinionated that the user doesn't get to make their own choices to support their preferred and most comfortable workflow. I want to be able to use your tool — a tool for which I am grateful for the investment of your time and energy. But I want to be able to use it as I need it—which is that it only pops up when I need it and not every time I click a URL.

**Comment by will-stone** [comment]
No worries.

If this were commercial software, I'd totally understand your point of view: you have a reasonable request. One of my favourite open-source projects is Elementary OS (if I weren't on a MacBook, I'd probably be using that as my OS and recommend it to anyone looking to get away from Windows). They have wonderful [Human Interface Guidelines](https://elementary.io/docs/human-interface-guidelines#concision) akin to Apple's that states:

> settings mean more code, more bugs, more testing, more documentation, and more complexity.

I used to have a settings page for Browserosaurus, and I scrapped it in favour of the current one-size-fits-most strategy. I love the simplicity of the project at the moment, and am looking to keep it this way for the foreseeable future. But like I said, don't be afraid to suggest other improvements. Or have a go at the code, I'm happy to review a PR if you can get your desired functionality into the app, and answer any questions you may have about getting it up-and-running locally.
